### PR TITLE
Add release action

### LINKED ISSUE #73: Publish to OpenVSX
Hi @KamasamaK!

Unfortunately, Microsoft prohibits the usage of the MS Extension Marketplace by any other non-microsoft products. Because of this, we kindly ask you to take the ownership of your namespace in OpenVSX and publish there as well.

OpenVSX is a vendor neutral alternative to the MS Marketplace used by all other derivatives of VS Code like Gitpod, OpenVSCode, VSCodium, Theia based IDEs, and so on.

The docs for publishing the extension are here: [eclipse/openvsx/wiki/Publishing-Extensions](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). Technically this should be straightforward. You get a token and call `ovsx publish` with it. For example, this is how RedHat publishes their java extension: https://github.com/redhat-developer/vscode-java/blob/5d4f8d58b8e919534800ca7bc41e8513c288f573/Jenkinsfile#L78-L82.

Please do let me know if you are open to receive a PR contributing a release GitHub Action both to MS marketplace and OpenVSX. I'd love to help out! 

PS. It would also be great if we could publish https://github.com/KamasamaK/vscode-cflint to OpenVSX as well.

### PR DESCRIPTION
**Pull request by filiptronicek**
Add a GitHub Action that creates a GitHub Release and publishes the extension to both the Microsoft Marketplace and OpenVSX.

This fixes #73 

An example release can be found at https://github.com/filiptronicek/vscode-cfml/releases/tag/release%2F0.5.3,

In addition to the now-working release publishing, for publishing to the marketplaces to work, two new repository secrets will need to be configured:
- `VSCE_PAT` - the token for publishing to Microsoft's Marketplace
- `OVSX_PAT` - the token for publishing to OpenVSX. To get this token, you will have to sign up for [OpenVSX](https://open-vsx.org/), sign the CLA and get a token from the dashboard

### CODE REVIEW

**Comment by filiptronicek** [comment]
@KamasamaK are you planning on releasing a new version of the extension sometime soon? Because if not, could you please trigger a manual publish from the GitHub Action, so that we know whether everything turned out correctly? 😄

**Comment by KamasamaK** [comment]
@filiptronicek Yes, soon. I'm still looking to make some more minor changes first.

I want to point out that since `.github` was newly added, it's a good idea to also add it to `.vscodeignore` so I've done that.

I also have a couple questions. 
- Your instructions don't mention anything about namespace, but I assume I need to follow [these instructions](https://www.npmjs.com/package/ovsx#create-a-namespace) to create my namespace and then [claim ownership](https://github.com/eclipse/openvsx/wiki/Namespace-Access#how-to-claim-a-namespace) before publishing. Is that correct?
- Do you have any recommendations for Open VSX badges?

**Comment by filiptronicek** [comment]
> @filiptronicek Yes, soon. I'm still looking to make some more minor changes first.

Great! Please do ping me if there are any questions or errors you run into

> Your instructions don't mention anything about namespace, but I assume I need to follow these instructions to create my namespace and then claim ownership before publishing. Is that correct?

Exactly, forgot to add this in my instructions, but this is how you would approach it. 

> Do you have any recommendations for Open VSX badges?

There are two pretty nice README badges on [shields.io](https://shields.io/category/downloads) (on the page search for `Open VSX`), those are the only ones I am aware of ATM 😄

**Comment by KamasamaK** [comment]
Still waiting on EclipseFdn/open-vsx.org#806 before I do a release.

**Comment by KamasamaK** [comment]
@filiptronicek All good

**Pull request merged**
